# Generated by Django 3.0.6 on 2020-05-31 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
