# Generated by Django 3.0.6 on 2020-06-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_auto_20200531_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
