# Generated by Django 3.0.7 on 2020-06-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0012_auto_20200626_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='image',
        ),
    ]
